name: auth_feature
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bcrypt: ^1.1.3
  crypto: ^3.0.7
  dart_frog: ^1.1.0
  dart_jsonwebtoken: ^3.3.1
  dotenv: ^4.2.0
  stormberry: ^0.18.0

dev_dependencies:
  build_runner: ^2.10.4
  dart_frog_lint: ^0.1.0
  mocktail: ^1.0.3
  test: ^1.25.5
